### ISSUE TITLE
Одинаковые migrations для test и prod

### ISSUE THREAD

**Issue by zhekazuev** [luchanos/luchanos_oxford_university#5]
Привет.

Пришел с твоего видео об этом проекте и вижу, что используешь немного запутанный подход для миграций перед тестами, цитирую:
> ...с первого раза все должно упасть

Возможно ли использовать те же файлы миграций, но для тестовой базы данных?
Или использовать alembic для нескольких бд, как сделал товарищ [тут](https://medium.com/pythonistas/managing-multiple-databases-migrations-with-alembic-10025a4b3ab3) или как описано в [документации](https://alembic.sqlalchemy.org/en/latest/cookbook.html#multiple-environments)?
``` ini
[DEFAULT]
# all defaults shared between environments go here

sqlalchemy.url = postgresql://scott:tiger@hostname/mydatabase


[schema1]
# path to env.py and migration scripts for schema1
script_location = myproject/revisions/schema1

[schema2]
# path to env.py and migration scripts for schema2
script_location = myproject/revisions/schema2

[schema3]
# path to env.py and migration scripts for schema3
script_location = myproject/revisions/db2

# this schema uses a different database URL as well
sqlalchemy.url = postgresql://scott:tiger@hostname/myotherdatabase
```

[Пример миграций от Яндекса](https://github.com/alvassin/alembic-quickstart).

Грубо говоря сделать так: когда запускаешь тесты, то будут использованы все те же миграции, но на тестовую базу данных. 
Это дает нам большую схожесть между тестовой средой и `боевой`, но с разным адресом базы данных, только и всего.

Выглядеть это может примерно так, но сейчас нет возможности проверить работоспособность данного решения:

`settings.py` - идентичный существующему:
```
...
REAL_DATABASE_URL = env.str(
    "REAL_DATABASE_URL",
    default="postgresql+asyncpg://postgres:postgres@0.0.0.0:5432/postgres",
)  # connect string for the real database

TEST_DATABASE_URL = env.str(
    "TEST_DATABASE_URL",
    default="postgresql+asyncpg://postgres_test:postgres_test@0.0.0.0:5433/postgres_test",
)  # connect string for the test database
```

`tests/conftest.py`:
```python
...
@pytest.fixture(scope="session", autouse=True)
async def run_migrations():
    # только накатывание миграций - без генерации папки tests/migrations на данном этапе
    os.system('alembic -n test revision --autogenerate -m "test running migrations"')
    os.system("alembic upgrade heads")
...
```

`migrations/env.py`:
```python
db_name = config.config_ini_section # active config ini section is the db name that we have chosen
config.set_main_option(
    "sqlalchemy.url",
    f'{os.environ["SQLALCHEMY_DATABASE_URL"]}/{db_name}'
)
```

`migrations/alembic.ini` - пример [отсюда](https://stackoverflow.com/questions/37890284/ini-file-load-environment-variable) и [отсюда](https://medium.com/pythonistas/managing-multiple-databases-migrations-with-alembic-10025a4b3ab3):
```ini
...
databases = prod, tests
[prod]
sqlalchemy.url = postgresql://postgres:postgres@0.0.0.0/postgresql
# если желаешь использовать отдельные подпапки для миграций
version_locations = ./migrations/prod
[test]
sqlalchemy.url = postgresql://postgresql_test:postgresql_test@0.0.0.0/postgresql_test
# если желаешь использовать отдельные подпапки для миграций
version_locations = ./migrations/test
...
```

В конечном итоге я подвожу к тому, что стоит использовать одни и те же миграции, но только меняя URL.

P.S. Я попробую протестировать при возможности и исправить данный issue, добавив актуальные изменения.

**Comment by luchanos** [comment]
Огромное тебе спасибо! Я в последних роликах что-то подобное сделал) Завтра утром встану и попробую доработать код с учетом твоих правок! Крепко жму твою руку!

**Comment by zhekazuev** [comment]
Привет.
Забыл я про этот тикет, так и не протестил.

Пожалуйста.
😎👉👈
